DELETE http://localhost:3000/delete_book/3
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNocmV5YXNoQGdtYWlsLmNvbSIsImV4cCI6MTcwNzU4ODc5OCwiaWQiOjF9.h6A2mwLb0XZOeA3g-4wBmtsibHPqcFfoh7p1jNFgrzc